name: Publish package to pypi

on:
  workflow_dispatch:
  push: 

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - id: get_status
        name: get_status
        uses: ./.github/actions/get_status
        with:
         package_name: lock-defaults

      - name: Show diff results
        shell: bash
        run : |
          echo "$remote_exists"
          echo "${{ steps.get_status.outputs.version_difference }}"
        env:
          remote_exists: ${{ steps.tests.outputs.stdout }}