name: "Run tests and publish (if new version)"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Fetch repo name
        id: repo_name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"

      - id: get_status
        name: get_status
        uses: ./.github/actions/get_status
        with:
         package_name: ${{ steps.repo_name.outputs.value }}

      - name: Show diff results
        shell: bash
        run : |
          echo "${{ steps.get_status.outputs.remote_exists }}"
          echo "${{ steps.get_status.outputs.version_difference }}"

      - name: gated results
        if: ${{ steps.get_status.outputs.remote_exists == 'true' && steps.get_status.outputs.version_difference == 'true'}}
        shell: bash
        run : |
          echo "this runs"